/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const DemoComputer = (props) => {
    const { nodes, materials } = useGLTF("src/Models/Gondola.glb")
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gondola_Final_Baked.geometry}
                material={materials.Gondola_Final_Baked}
            />
        </group>
    )
}

useGLTF.preload("src/Models/Gondola.glb")

export default DemoComputer;